# Generated by Django 5.1.1 on 2024-09-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_pdfupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFUpload',
        ),
    ]
