# Generated by Django 5.1.1 on 2024-09-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_overtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='horas_extras',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='mes',
            field=models.CharField(max_length=7),
        ),
    ]
