# Generated by Django 5.1.1 on 2024-09-24 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_alter_overtime_horas_extras_alter_overtime_mes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=100)),
                ('contrato_numero', models.CharField(max_length=100)),
                ('total_horas_extras_decimal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('horas_totales_decimal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('horas_complementarias_decimal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
