# Generated by Django 5.1.1 on 2024-09-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_overtimedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overtimedata',
            old_name='created_at',
            new_name='fecha_subida',
        ),
        migrations.RemoveField(
            model_name='overtimedata',
            name='horas_totales_decimal',
        ),
        migrations.AlterField(
            model_name='overtimedata',
            name='contrato_numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='overtimedata',
            name='mes',
            field=models.CharField(max_length=20),
        ),
    ]
